import { z } from 'zod';
import { INCLUDE_PROPRIETARY } from '@/config';
import {
  abilityRulesSchema,
  backgroundDefSchema,
  classDefSchema,
  equipmentDefSchema,
  featureDefSchema,
  heritageDefSchema,
  lineageDefSchema,
  skillDefSchema,
  spellDefSchema,
  subclassDefSchema,
  talentDefSchema,
} from '@/schema';

// Open content is generated by the ingestion script (src/scripts/ingest.ts)
// from the Black Flag Reference Document. Proprietary, Player's-Guide-only
// content lives in the parallel *.proprietary.json files and is kept entirely
// separate so a shareable build can exclude it (see config.ts / BUILD_PROFILE).
// The *.proprietary.json files are empty stubs until sourced from the owner's
// Player's Guide PDF — and must never be distributed once populated.
import classesOpen from './classes.open.json';
import classesProp from './classes.proprietary.json';
import subclassesOpen from './subclasses.open.json';
import subclassesProp from './subclasses.proprietary.json';
import featuresOpen from './features.open.json';
import featuresProp from './features.proprietary.json';
import lineagesOpen from './lineages.open.json';
import lineagesProp from './lineages.proprietary.json';
import heritagesOpen from './heritages.open.json';
import heritagesProp from './heritages.proprietary.json';
import backgroundsOpen from './backgrounds.open.json';
import backgroundsProp from './backgrounds.proprietary.json';
import talentsOpen from './talents.open.json';
import talentsProp from './talents.proprietary.json';
import spellsOpen from './spells.open.json';
import spellsProp from './spells.proprietary.json';
import equipmentOpen from './equipment.open.json';
import equipmentProp from './equipment.proprietary.json';

// System rules config (not licensed content; not profile-filtered).
import skillsRaw from './skills.json';
import abilityRulesRaw from './abilityRules.json';

/** Drop proprietary records unless this is a personal build. Pure + testable. */
export function selectByProfile<T extends { source: 'open' | 'proprietary' }>(
  records: T[],
  includeProprietary: boolean,
): T[] {
  return includeProprietary
    ? records
    : records.filter((r) => r.source === 'open');
}

/**
 * Validate the open + proprietary record arrays for one content type, merge
 * them, and drop proprietary records unless this is a personal build. Parsing
 * here means bad data fails loudly at startup rather than deep inside the UI.
 */
function load<S extends z.ZodType<{ source: 'open' | 'proprietary' }>>(
  schema: S,
  open: unknown,
  proprietary: unknown,
  label: string,
): z.infer<S>[] {
  const arr = z.array(schema);
  const openParsed = arr.safeParse(open);
  if (!openParsed.success) {
    throw new Error(`Invalid open content in ${label}: ${openParsed.error.message}`);
  }
  const records = [...openParsed.data];

  if (INCLUDE_PROPRIETARY) {
    const propParsed = arr.safeParse(proprietary);
    if (!propParsed.success) {
      throw new Error(
        `Invalid proprietary content in ${label}: ${propParsed.error.message}`,
      );
    }
    records.push(...propParsed.data);
  }

  // Belt-and-suspenders: never let a proprietary record survive a shareable build.
  return selectByProfile(records, INCLUDE_PROPRIETARY);
}

export const classes = load(classDefSchema, classesOpen, classesProp, 'classes');
export const subclasses = load(
  subclassDefSchema,
  subclassesOpen,
  subclassesProp,
  'subclasses',
);
export const features = load(
  featureDefSchema,
  featuresOpen,
  featuresProp,
  'features',
);
export const lineages = load(
  lineageDefSchema,
  lineagesOpen,
  lineagesProp,
  'lineages',
);
export const heritages = load(
  heritageDefSchema,
  heritagesOpen,
  heritagesProp,
  'heritages',
);
export const backgrounds = load(
  backgroundDefSchema,
  backgroundsOpen,
  backgroundsProp,
  'backgrounds',
);
export const talents = load(talentDefSchema, talentsOpen, talentsProp, 'talents');
export const spells = load(spellDefSchema, spellsOpen, spellsProp, 'spells');
export const equipment = load(
  equipmentDefSchema,
  equipmentOpen,
  equipmentProp,
  'equipment',
);

/** Skill -> ability map (18 skills). */
export const skills = z.array(skillDefSchema).parse(skillsRaw);
/** Standard array, point-buy costs, and creation bonuses. */
export const abilityRules = abilityRulesSchema.parse(abilityRulesRaw);

export const contentData = {
  classes,
  subclasses,
  features,
  lineages,
  heritages,
  backgrounds,
  talents,
  spells,
  equipment,
};
