import { z } from 'zod';
import {
  abilityKeySchema,
  circleSchema,
  sourceSchema,
  traditionSchema,
} from './common';

/**
 * Content definitions — the shipped JSON generated by ingestion (Section 5).
 * These shapes will firm up against real BFRD data in M2; the goal here is to
 * lock the contract and the `source` namespacing early.
 *
 * Every content record carries `source` so a `shareable` build can exclude
 * proprietary records cleanly (see config.ts / BUILD_PROFILE).
 */

/** Fields common to every content record. */
const contentBase = {
  id: z.string().min(1),
  name: z.string().min(1),
  source: sourceSchema,
  /** Free-form attribution / citation line for the About screen. */
  attribution: z.string().optional(),
};

/** One row of a class progression table (per character level). */
export const progressionRowSchema = z.object({
  level: z.number().int().min(1).max(20),
  proficiencyBonus: z.number().int().min(2).max(6),
  /** Feature ids granted at this level (auto-applied during leveling). */
  features: z.array(z.string()).default([]),
  /** True on the level where this class chooses its subclass. */
  subclassChoice: z.boolean().default(false),
  /** True on a level that grants an ability-score-increase-or-talent choice. */
  asiOrTalent: z.boolean().default(false),
  /**
   * Spell-slot counts by circle for casters, index 1..9 (cantrips tracked
   * separately as `cantripsKnown`). Omitted for non-casters.
   */
  spellSlots: z.array(z.number().int().min(0)).optional(),
  cantripsKnown: z.number().int().min(0).optional(),
});
export type ProgressionRow = z.infer<typeof progressionRowSchema>;

export const spellcastingTypeSchema = z.enum([
  'none',
  'full',
  'half',
  'third',
  'pact',
]);
export type SpellcastingType = z.infer<typeof spellcastingTypeSchema>;

export const classDefSchema = z.object({
  ...contentBase,
  hitDie: z.number().int().refine((d) => [6, 8, 10, 12].includes(d), {
    message: 'hitDie must be one of 6, 8, 10, 12',
  }),
  primaryAbilities: z.array(abilityKeySchema).min(1),
  savingThrowProficiencies: z.array(abilityKeySchema),
  /** Skills the class may choose, plus how many to pick. */
  skillChoices: z.object({
    choose: z.number().int().min(0),
    from: z.array(z.string()),
  }),
  progressionTable: z.array(progressionRowSchema).length(20),
  /** Item ids forming the default equipment kit. */
  equipmentKit: z.array(z.string()).default([]),
  spellcasting: spellcastingTypeSchema.default('none'),
  /** Ability used for spellcasting, when a caster. */
  spellcastingAbility: abilityKeySchema.optional(),
  summary: z.string().optional(),
});
export type ClassDef = z.infer<typeof classDefSchema>;

export const subclassDefSchema = z.object({
  ...contentBase,
  classId: z.string().min(1),
  /** Feature ids keyed by the level at which they are gained. */
  featuresByLevel: z.record(z.string(), z.array(z.string())).default({}),
  summary: z.string().optional(),
});
export type SubclassDef = z.infer<typeof subclassDefSchema>;

/**
 * A discrete class/subclass/lineage/heritage feature. Referenced by id from
 * class progression tables, subclass featuresByLevel, and lineage/heritage
 * trait lists so the rules text can be shown when the feature is gained.
 */
export const featureDefSchema = z.object({
  ...contentBase,
  kind: z.enum(['class', 'subclass', 'lineage', 'heritage']),
  /** Id of the class/subclass/lineage/heritage that grants this feature. */
  parentId: z.string().min(1),
  /** Level at which it is gained (class/subclass features); omitted otherwise. */
  level: z.number().int().min(0).max(20).optional(),
  description: z.string().default(''),
});
export type FeatureDef = z.infer<typeof featureDefSchema>;

export const lineageDefSchema = z.object({
  ...contentBase,
  size: z.enum(['Small', 'Medium']),
  speed: z.number().int().min(0),
  /** Lifespan / flavor note. */
  lifespan: z.string().optional(),
  traits: z.array(z.string()).default([]),
  description: z.string().optional(),
});
export type LineageDef = z.infer<typeof lineageDefSchema>;

export const heritageDefSchema = z.object({
  ...contentBase,
  skillProficiencies: z.array(z.string()).default([]),
  languages: z.array(z.string()).default([]),
  trait: z.string().optional(),
  description: z.string().optional(),
});
export type HeritageDef = z.infer<typeof heritageDefSchema>;

export const backgroundDefSchema = z.object({
  ...contentBase,
  skillProficiencies: z.array(z.string()).default([]),
  /** Choose-N skills when the background offers a choice. */
  skillChoices: z
    .object({ choose: z.number().int().min(0), from: z.array(z.string()) })
    .optional(),
  /** A background grants one talent in ToV. */
  grantedTalent: z.string().optional(),
  languages: z.array(z.string()).default([]),
  equipment: z.array(z.string()).default([]),
  description: z.string().optional(),
});
export type BackgroundDef = z.infer<typeof backgroundDefSchema>;

export const talentDefSchema = z.object({
  ...contentBase,
  category: z.enum(['Magic', 'Martial', 'Technical']),
  prerequisites: z.array(z.string()).default([]),
  effect: z.string(),
});
export type TalentDef = z.infer<typeof talentDefSchema>;

export const spellDefSchema = z.object({
  ...contentBase,
  circle: circleSchema,
  tradition: traditionSchema,
  castingTime: z.string(),
  range: z.string(),
  components: z.string(),
  duration: z.string(),
  description: z.string(),
  /** Class ids that can learn this spell. */
  classLists: z.array(z.string()).default([]),
});
export type SpellDef = z.infer<typeof spellDefSchema>;

export const equipmentDefSchema = z.object({
  ...contentBase,
  category: z.enum(['weapon', 'armor', 'gear']),
  cost: z.string().optional(),
  weight: z.number().optional(),
  /** Armor-only: base AC and how Dex applies. */
  armor: z
    .object({
      category: z.enum(['light', 'medium', 'heavy', 'shield']),
      baseAc: z.number().int(),
      dexBonus: z.enum(['none', 'capped', 'full']),
      dexCap: z.number().int().optional(),
      stealthDisadvantage: z.boolean().default(false),
    })
    .optional(),
  /** Weapon-only: damage and properties. */
  weapon: z
    .object({
      damage: z.string(),
      damageType: z.string(),
      properties: z.array(z.string()).default([]),
    })
    .optional(),
});
export type EquipmentDef = z.infer<typeof equipmentDefSchema>;

/**
 * System rules config (not licensed "content", so not namespaced open/proprietary).
 * Generated by ingestion from the Foundry system config to avoid transcription.
 */
export const skillDefSchema = z.object({
  key: z.string().min(1),
  label: z.string().min(1),
  ability: abilityKeySchema,
});
export type SkillDef = z.infer<typeof skillDefSchema>;

export const abilityRulesSchema = z.object({
  standardArray: z.array(z.number().int()),
  pointBuy: z.object({
    points: z.number().int(),
    costs: z.record(z.string(), z.number().int()),
  }),
  /** The lineage-independent ability bumps (+2 / +1) applied at creation. */
  bonuses: z.array(z.number().int()),
  rolling: z.object({ formula: z.string(), max: z.number().int() }),
});
export type AbilityRules = z.infer<typeof abilityRulesSchema>;
